"""Proto closure, SOURCE, `_gen` headers and hash-lock files for regen.sh.

Standard library only, and it imports nothing from this repository, so
`regen.sh` and `repin.py` load nothing else. `regen.sh` calls `main` for the
steps that are easier here than in shell.
"""

from __future__ import annotations

import hashlib
import os
import re
import subprocess
import sys
from typing import (Callable, Dict, Iterable, List, Mapping, Optional,
                    Sequence, Tuple)

PROTO_ROOT = "gateway_interceptor.proto"
SOURCE_NAME = "SOURCE"
GEN_MARK = ("# Generated by interceptor/regen.sh from OpenShell's protos. "
            "Do not edit.")
SOURCE_MARK = "# OpenShell protos vendored by interceptor/regen.sh. Do not edit."
LOCK_MARK = "# Generated by interceptor/regen.sh --apply. Do not edit."
LOCK_INSTALL = ("# Install: pip install --require-hashes --only-binary=:all: "
                "-r <file>")

_IMPORT = re.compile(r'^\s*import\s+(?:public\s+|weak\s+)?"([^"]+)"\s*;', re.M)
_SHA = re.compile(r"[0-9a-f]{64}\Z")
_COMMIT = re.compile(r"[0-9a-f]{40}\Z")


def normalize(name: str) -> str:
    """PEP 503 name normalization."""
    return re.sub(r"[-_.]+", "-", name).lower()


def wheel_pin(filename: str) -> Tuple[str, str]:
    """`(normalized name, version)` from a PEP 427 wheel filename."""
    base = os.path.basename(filename)
    if not base.endswith(".whl"):
        raise ValueError(f"{filename!r} is not a wheel")
    parts = base[:-4].split("-")
    if len(parts) < 5:
        raise ValueError(f"{filename!r} is not a wheel filename")
    return normalize(parts[0]), parts[1]


def proto_imports(text: str) -> List[str]:
    """The `import "x.proto";` targets, Google's excluded."""
    return [m for m in _IMPORT.findall(text) if not m.startswith("google/")]


def import_closure(read: Callable[[str], str],
                   root: str = PROTO_ROOT) -> List[str]:
    """Every proto `root` imports, directly or not, and `root`; sorted."""
    seen: List[str] = []
    todo = [root]
    while todo:
        f = todo.pop()
        if f in seen:
            continue
        seen.append(f)
        todo.extend(proto_imports(read(f)))
    return sorted(seen)


def _digest_lines(digests: Mapping[str, str]) -> List[str]:
    return [f"sha256 {digests[f]}  {f}" for f in sorted(digests)]


def source_text(tag: str, commit: str, digests: Mapping[str, str]) -> str:
    lines = [SOURCE_MARK, f"tag {tag}", f"commit {commit}"]
    lines += _digest_lines(digests)
    return "\n".join(lines) + "\n"


def read_source(path: str) -> Tuple[str, str, Dict[str, str]]:
    """`(tag, commit, {file: sha256})`. ValueError on a malformed file."""
    with open(path, encoding="utf-8") as fh:
        lines = [ln for ln in fh.read().splitlines()
                 if ln.strip() and not ln.startswith("#")]
    tag = commit = None
    digests: Dict[str, str] = {}
    for ln in lines:
        w = ln.split()
        if len(w) == 2 and w[0] == "tag":
            tag = w[1]
        elif len(w) == 2 and w[0] == "commit" and _COMMIT.match(w[1]):
            commit = w[1]
        elif len(w) == 3 and w[0] == "sha256" and _SHA.match(w[1]):
            digests[w[2]] = w[1]
        else:
            raise ValueError(f"{path}: malformed line {ln!r}")
    if not tag or not commit or not digests:
        raise ValueError(f"{path}: needs a tag, a commit and a digest")
    return tag, commit, digests


def gen_header(tag: str, digests: Mapping[str, str]) -> str:
    lines = [GEN_MARK, f"# source-tag {tag}"]
    lines += ["# " + ln for ln in _digest_lines(digests)]
    return "\n".join(lines) + "\n\n"


def parse_pip_hash(text: str) -> Dict[str, List[str]]:
    """The output of `pip hash f1 f2 ...`, keyed by file basename."""
    out: Dict[str, List[str]] = {}
    cur: Optional[str] = None
    for ln in text.splitlines():
        ln = ln.strip()
        if ln.endswith(":") and ln != ":":
            cur = os.path.basename(ln[:-1])
            out.setdefault(cur, [])
        elif ln.startswith("--hash=sha256:") and cur is not None:
            out[cur].append(ln.split(":", 1)[1])
    return out


def lock_text(top: Sequence[str], pins: Mapping[str, str],
              hashes: Mapping[str, Iterable[str]], targets: str) -> str:
    for t in top:
        if t not in pins:
            raise ValueError(f"top-level {t} is not pinned")
    order = list(top) + sorted(n for n in pins if n not in top)
    lines = [LOCK_MARK, LOCK_INSTALL, "# top-level: " + " ".join(top),
             "# targets: " + targets]
    for n in order:
        hs = sorted(set(hashes.get(n, ())))
        if not hs:
            raise ValueError(f"{n} has no hash")
        lines.append(f"{n}=={pins[n]} \\")
        lines.append(" \\\n".join(f"    --hash=sha256:{h}" for h in hs))
    return "\n".join(lines) + "\n"


def _read_pins(path: str) -> Dict[str, str]:
    out: Dict[str, str] = {}
    with open(path, encoding="utf-8") as fh:
        for ln in fh.read().split():
            n, _, v = ln.partition("==")
            out[n] = v
    return out


def _git_show(repo: str, tag: str, f: str) -> str:
    r = subprocess.run(["git", "-C", repo, "show", f"{tag}:proto/{f}"],
                       capture_output=True, text=True, check=True)
    return r.stdout


def main(argv: Optional[Sequence[str]] = None) -> int:
    a = list(sys.argv[1:] if argv is None else argv)
    try:
        if len(a) == 3 and a[0] == "closure":
            for f in import_closure(lambda f: _git_show(a[1], a[2], f)):
                print(f)
            return 0
        if len(a) == 4 and a[0] == "source":
            files = sorted(f for f in os.listdir(a[1]) if f.endswith(".proto"))
            digests = {}
            for f in files:
                with open(os.path.join(a[1], f), "rb") as fh:
                    digests[f] = hashlib.sha256(fh.read()).hexdigest()
            with open(os.path.join(a[1], SOURCE_NAME), "w",
                      encoding="utf-8") as fh:
                fh.write(source_text(a[2], a[3], digests))
            return 0
        if len(a) == 3 and a[0] == "stamp":
            tag, _, digests = read_source(os.path.join(a[1], SOURCE_NAME))
            head = gen_header(tag, digests)
            for f in sorted(os.listdir(a[2])):
                if f.endswith(".py"):
                    p = os.path.join(a[2], f)
                    with open(p, encoding="utf-8") as fh:
                        body = fh.read()
                    with open(p, "w", encoding="utf-8") as fh:
                        fh.write(head + body)
            return 0
        if len(a) == 2 and a[0] == "pins":
            found: Dict[str, str] = {}
            for f in sorted(os.listdir(a[1])):
                if f.endswith(".whl"):
                    n, v = wheel_pin(f)
                    if found.setdefault(n, v) != v:
                        print(f"{n} has two versions: {found[n]} and {v}",
                              file=sys.stderr)
                        return 1
            for n in sorted(found):
                print(f"{n}=={found[n]}")
            return 0
        if len(a) == 5 and a[0] == "lock":
            pins = _read_pins(a[3])
            parsed = parse_pip_hash(sys.stdin.read())
            hashes: Dict[str, List[str]] = {}
            for f, hs in parsed.items():
                n, v = wheel_pin(f)
                if pins.get(n) == v:
                    hashes.setdefault(n, []).extend(hs)
            tops = [t for t in a[2].split(",") if t]
            with open(a[1], "w", encoding="utf-8") as fh:
                fh.write(lock_text(tops, pins, hashes, a[4]))
            return 0
    except (ValueError, OSError, subprocess.CalledProcessError) as e:
        print(f"locks: {e}", file=sys.stderr)
        return 1
    print("usage: locks.py closure DIR TAG | source PROTO_DIR TAG COMMIT | "
          "stamp PROTO_DIR GEN_DIR | pins DIR | lock OUT TOPS PINSFILE TARGETS",
          file=sys.stderr)
    return 2


if __name__ == "__main__":
    sys.exit(main())
