# Generated by interceptor/regen.sh from OpenShell's protos. Do not edit.
# source-tag v0.1.2
# sha256 e50bd875a760f54b80269c65ee47984cae424fb623b7f59551ba62550c23e70b  datamodel.proto
# sha256 60f28ee9dc846d41152f4db7e82a439c78d024786efaceb464900d1d1ad129ad  extension.proto
# sha256 931411aaae512b41117039f35b8c8727c8aefa87e898879e8b6f277c0149f79d  gateway_interceptor.proto
# sha256 2e31d0faca652b91729f88bd4053447e5d162e74de7dbacdcc06327ed82e5b95  openshell.proto
# sha256 10c8a99b505047f759951285fdae6068afd267ef672d00a65385a91ee8d027ee  options.proto
# sha256 ed3d2650c8d1c4cbb653259c6055adba2dba8a51498ab6a1b2cfc339997ab2b9  sandbox.proto

# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: extension.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'extension.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x65xtension.proto\x12\x16openshell.extension.v1\"/\n\x0fProtocolVersion\x12\r\n\x05major\x18\x01 \x01(\r\x12\r\n\x05minor\x18\x02 \x01(\r\"\xcd\x01\n\x0cPeerMetadata\x12\x41\n\x10protocol_version\x18\x01 \x01(\x0b\x32\'.openshell.extension.v1.ProtocolVersion\x12\x1b\n\x13implementation_name\x18\x02 \x01(\t\x12\x1e\n\x16implementation_version\x18\x03 \x01(\t\x12\x1e\n\x16supported_capabilities\x18\x04 \x03(\t\x12\x1d\n\x15required_capabilities\x18\x05 \x03(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'extension_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PROTOCOLVERSION']._serialized_start=43
  _globals['_PROTOCOLVERSION']._serialized_end=90
  _globals['_PEERMETADATA']._serialized_start=93
  _globals['_PEERMETADATA']._serialized_end=298
# @@protoc_insertion_point(module_scope)
