# Generated by interceptor/regen.sh from OpenShell's protos. Do not edit.
# source-tag v0.1.3
# sha256 e50bd875a760f54b80269c65ee47984cae424fb623b7f59551ba62550c23e70b  datamodel.proto
# sha256 60f28ee9dc846d41152f4db7e82a439c78d024786efaceb464900d1d1ad129ad  extension.proto
# sha256 931411aaae512b41117039f35b8c8727c8aefa87e898879e8b6f277c0149f79d  gateway_interceptor.proto
# sha256 3f0f7ca84819725e27b41ce5f603b536db9450c660afc906445b53dc4776c7ea  openshell.proto
# sha256 10c8a99b505047f759951285fdae6068afd267ef672d00a65385a91ee8d027ee  options.proto
# sha256 d06089ccd15b57519adb3236e7a4c16661c7c52c9f184f2f826246c62e090839  sandbox.proto

# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import gateway_interceptor_pb2 as gateway__interceptor__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in gateway_interceptor_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GatewayInterceptorStub(object):
    """GatewayInterceptor lets an external governance service evaluate gateway
    control-plane operations after OpenShell admission and before or after the
    gateway applies the operation.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Describe = channel.unary_unary(
                '/openshell.gateway_interceptor.v1.GatewayInterceptor/Describe',
                request_serializer=gateway__interceptor__pb2.DescribeRequest.SerializeToString,
                response_deserializer=gateway__interceptor__pb2.InterceptorManifest.FromString,
                _registered_method=True)
        self.SnapshotProviderProfiles = channel.unary_unary(
                '/openshell.gateway_interceptor.v1.GatewayInterceptor/SnapshotProviderProfiles',
                request_serializer=gateway__interceptor__pb2.ProviderProfileSnapshotRequest.SerializeToString,
                response_deserializer=gateway__interceptor__pb2.ProviderProfileSnapshot.FromString,
                _registered_method=True)
        self.Evaluate = channel.unary_unary(
                '/openshell.gateway_interceptor.v1.GatewayInterceptor/Evaluate',
                request_serializer=gateway__interceptor__pb2.InterceptorEvaluation.SerializeToString,
                response_deserializer=gateway__interceptor__pb2.InterceptorResult.FromString,
                _registered_method=True)


class GatewayInterceptorServicer(object):
    """GatewayInterceptor lets an external governance service evaluate gateway
    control-plane operations after OpenShell admission and before or after the
    gateway applies the operation.
    """

    def Describe(self, request, context):
        """Describe returns the interceptor manifest and declared bindings.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SnapshotProviderProfiles(self, request, context):
        """SnapshotProviderProfiles returns the interceptor's current provider
        profile snapshot when the manifest advertises provider_profiles = true.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Evaluate(self, request, context):
        """Evaluate returns an allow, deny, or mutation decision for one operation
        phase.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GatewayInterceptorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Describe': grpc.unary_unary_rpc_method_handler(
                    servicer.Describe,
                    request_deserializer=gateway__interceptor__pb2.DescribeRequest.FromString,
                    response_serializer=gateway__interceptor__pb2.InterceptorManifest.SerializeToString,
            ),
            'SnapshotProviderProfiles': grpc.unary_unary_rpc_method_handler(
                    servicer.SnapshotProviderProfiles,
                    request_deserializer=gateway__interceptor__pb2.ProviderProfileSnapshotRequest.FromString,
                    response_serializer=gateway__interceptor__pb2.ProviderProfileSnapshot.SerializeToString,
            ),
            'Evaluate': grpc.unary_unary_rpc_method_handler(
                    servicer.Evaluate,
                    request_deserializer=gateway__interceptor__pb2.InterceptorEvaluation.FromString,
                    response_serializer=gateway__interceptor__pb2.InterceptorResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'openshell.gateway_interceptor.v1.GatewayInterceptor', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('openshell.gateway_interceptor.v1.GatewayInterceptor', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GatewayInterceptor(object):
    """GatewayInterceptor lets an external governance service evaluate gateway
    control-plane operations after OpenShell admission and before or after the
    gateway applies the operation.
    """

    @staticmethod
    def Describe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/openshell.gateway_interceptor.v1.GatewayInterceptor/Describe',
            gateway__interceptor__pb2.DescribeRequest.SerializeToString,
            gateway__interceptor__pb2.InterceptorManifest.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SnapshotProviderProfiles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/openshell.gateway_interceptor.v1.GatewayInterceptor/SnapshotProviderProfiles',
            gateway__interceptor__pb2.ProviderProfileSnapshotRequest.SerializeToString,
            gateway__interceptor__pb2.ProviderProfileSnapshot.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Evaluate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/openshell.gateway_interceptor.v1.GatewayInterceptor/Evaluate',
            gateway__interceptor__pb2.InterceptorEvaluation.SerializeToString,
            gateway__interceptor__pb2.InterceptorResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
