# Generated by interceptor/regen.sh from OpenShell's protos. Do not edit.
# source-tag v0.1.2
# sha256 e50bd875a760f54b80269c65ee47984cae424fb623b7f59551ba62550c23e70b  datamodel.proto
# sha256 60f28ee9dc846d41152f4db7e82a439c78d024786efaceb464900d1d1ad129ad  extension.proto
# sha256 931411aaae512b41117039f35b8c8727c8aefa87e898879e8b6f277c0149f79d  gateway_interceptor.proto
# sha256 2e31d0faca652b91729f88bd4053447e5d162e74de7dbacdcc06327ed82e5b95  openshell.proto
# sha256 10c8a99b505047f759951285fdae6068afd267ef672d00a65385a91ee8d027ee  options.proto
# sha256 ed3d2650c8d1c4cbb653259c6055adba2dba8a51498ab6a1b2cfc339997ab2b9  sandbox.proto

# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: options.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'options.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\roptions.proto\x12\x14openshell.options.v1\x1a google/protobuf/descriptor.proto\"b\n\x11\x41uthorizationRule\x12\x11\n\tauth_mode\x18\x01 \x01(\t\x12\x16\n\x0eworkspace_role\x18\x02 \x01(\t\x12\x13\n\x0bglobal_role\x18\x03 \x01(\t\x12\r\n\x05scope\x18\x04 \x01(\t:`\n\rauthorization\x12\x1e.google.protobuf.MethodOptions\x18\xd0\x86\x03 \x01(\x0b\x32\'.openshell.options.v1.AuthorizationRule:/\n\x06secret\x12\x1d.google.protobuf.FieldOptions\x18\xd1\x86\x03 \x01(\x08\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'options_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AUTHORIZATIONRULE']._serialized_start=73
  _globals['_AUTHORIZATIONRULE']._serialized_end=171
# @@protoc_insertion_point(module_scope)
