# Generated by interceptor/regen.sh from OpenShell's protos. Do not edit.
# source-tag v0.1.2
# sha256 e50bd875a760f54b80269c65ee47984cae424fb623b7f59551ba62550c23e70b  datamodel.proto
# sha256 60f28ee9dc846d41152f4db7e82a439c78d024786efaceb464900d1d1ad129ad  extension.proto
# sha256 931411aaae512b41117039f35b8c8727c8aefa87e898879e8b6f277c0149f79d  gateway_interceptor.proto
# sha256 2e31d0faca652b91729f88bd4053447e5d162e74de7dbacdcc06327ed82e5b95  openshell.proto
# sha256 10c8a99b505047f759951285fdae6068afd267ef672d00a65385a91ee8d027ee  options.proto
# sha256 ed3d2650c8d1c4cbb653259c6055adba2dba8a51498ab6a1b2cfc339997ab2b9  sandbox.proto

# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings


GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in options_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )
